site_name: Jobdone 使用指南
site_url: https://docs.jobdone.cc
site_description: Jobdone 工程現場與場域管理平台使用手冊

theme:
  name: material
  language: zh-TW
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切換深色模式
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切換淺色模式
  font:
    text: Noto Sans TC
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.tabs.link
    - toc.integrate

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 首頁: index.md
  - 歡迎使用Jobdone: welcome.md
  - 快速上手指南:
      - kuai-su-shang-shou-zhi-nan/index.md
      - 前置作業:
          - kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/index.md
          - 註冊: kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/zhu-ce.md
          - 建立 / 加入公司: kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/jian-li-jia-ru-gong-si.md
          - 功能授權: kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/gong-neng-shou-quan.md
          - 加入聯絡人: kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/jia-ru-lian-luo-ren.md
          - 建立公司專案: kuai-su-shang-shou-zhi-nan/qian-zhi-zuo-ye/jian-li-gong-si-zhuan-an.md
      - 派工單: kuai-su-shang-shou-zhi-nan/pai-gong-dan.md
      - 改善單: kuai-su-shang-shou-zhi-nan/gai-shan-dan.md
      - 釋疑單: kuai-su-shang-shou-zhi-nan/shi-yi-dan.md
      - 自主/自動檢查表: kuai-su-shang-shou-zhi-nan/zi-zhu-zi-dong-jian-cha-biao.md
      - 施工日誌: kuai-su-shang-shou-zhi-nan/shi-gong-ri-zhi.md
  - FAQ:
      - faq/index.md
      - 版本比較表: faq/ban-ben-bi-jiao-biao.md
      - 帳號與費用: faq/zhang-hao-yu-fei-yong.md
      - 系統疑難排解: faq/xi-tong-yi-nan-pai-jie.md
      - 系統需求: faq/xi-tong-xu-qiu.md
      - 裝置設定: faq/zhuang-zhi-she-ding.md
  - 個人帳號:
      - account/index.md
      - 註冊: account/sign_up.md
      - 個人資料: account/personinfo.md
      - 修改密碼: account/changepassword.md
      - 忘記密碼: account/forgetpassword.md
      - 通知: account/notify.md
      - 永久刪除帳號: account/delete.md
      - 我的改善單:
          - account/corrective_action/index.md
          - 填寫改善單: account/corrective_action/tian-xie-gai-shan-dan.md
          - 受文方內部審核: account/corrective_action/shou-wen-fang-nei-bu-shen-he.md
      - 我的派工單: account/wo-de-pai-gong-dan.md
      - 我的釋疑單( RFI ):
          - account/rfi/index.md
          - 發起釋疑單: account/rfi/fa-qi-shi-yi-dan.md
          - 釋疑單回覆: account/rfi/shi-yi-dan-hui-fu.md
  - 公司相關:
      - company_level/index.md
      - 建立公司資訊: company_level/regist.md
      - 加入公司: company_level/join_exit.md
      - 退出公司: company_level/tui-chu-gong-si.md
      - 成員權限管理: company_level/member.md
      - 部門管理: company_level/bu-men-guan-li.md
      - 付費流程: company_level/payment.md
      - 建立專案之前:
          - company_level/commonsetting/index.md
          - 新增工種 ( 工別 ) 類型: company_level/commonsetting/xin-zeng-gong-zhong-gong-bie-lei-xing.md
          - 新增機具類型: company_level/commonsetting/xin-zeng-ji-ju-lei-xing.md
          - 新增公司檢查範本: company_level/commonsetting/mainchecklist.md
  - 專案相關:
      - project_level/index.md
      - 專案清單/專案頁面: project_level/project_list.md
      - 新建專案: project_level/xin-jian-zhuan-an.md
      - 結案 / 刪除專案: project_level/jie-an-shan-chu-zhuan-an.md
      - 專案資訊: project_level/info.md
      - 專案經理 / 專案成員: project_level/member.md
      - 相關成員: project_level/xiang-guan-cheng-yuan.md
      - 協力廠商 / 外部聯絡人: project_level/contractor.md
      - 專案分項工程: project_level/subdivisional.md
      - 專案工種(工別)類型: project_level/zhuan-an-gong-zhong-gong-bie-lei-xing.md
      - 施工項目:
          - project_level/construction_item/index.md
          - 廠商 > 合約格式: project_level/construction_item/chang-shang-he-yue-ge-shi.md
          - 非廠商 > 合約格式: project_level/construction_item/fei-chang-shang-he-yue-ge-shi.md
          - 監造單位: project_level/construction_item/jian-zao-dan-wei.md
      - 施工項目總表: project_level/shi-gong-xiang-mu-zong-biao.md
      - 材料管理:
          - project_level/materials/index.md
          - 廠商 > 合約格式: project_level/materials/chang-shang-he-yue-ge-shi.md
          - 非廠商 > 合約格式: project_level/materials/fei-chang-shang-he-yue-ge-shi.md
      - 建地結構: project_level/construction_structure.md
      - 施工圖面: project_level/construction_drawing.md
      - 專案改善單:
          - project_level/corrective/index.md
          - 發起改善單: project_level/corrective/build.md
          - 轉發改善單: project_level/corrective/zhuan-fa-gai-shan-dan.md
          - 改善單審核: project_level/corrective/cap.md
          - 列印改善報告: project_level/corrective/close.md
      - 專案派工單: project_level/zhuan-an-pai-gong-dan.md
      - 文件中心**: project_level/wen-jian-zhong-xin.md
      - 圖說資料庫**: project_level/tu-shuo-zi-liao-ku.md
      - 申請與交付**: project_level/submittal.md
  - 模組、功能組合及功能: mo-zu-gong-neng-zu-he-ji-gong-neng.md
  - 一般建案 BC:
      - bc/index.md
      - 一般建案施工日誌: bc/yi-ban-jian-an-shi-gong-ri-zhi.md
      - 檢查表:
          - bc/qc/index.md
          - 檢查表設定: bc/qc/basic-settings.md
          - 設定專案檢查範本: bc/qc/template.md
          - 建立 / 執行檢查工作: bc/qc/implement-web.md
          - 審核檢查表: bc/qc/self-check-review-n-sign-web.md
          - 檢查表複驗: bc/qc/re-web.md
          - 列印檢查報告: bc/qc/print.md
      - 影音日誌: bc/media_diary.md
      - LINE 群組助理: bc/line.md
      - 會議紀錄: bc/meeting-minutes.md
  - 公共工程 PC:
      - pc/index.md
      - 公共工程施工日誌:
          - pc/pc_diary/index.md
          - 施工日誌:
              - pc/pc_diary/shi-gong-ri-zhi/index.md
              - 日誌 / 基本資訊: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-ji-ben-zi-xun.md
              - 日誌 / 施工概況: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-shi-gong-gai-kuang.md
              - 日誌 / 材料概況: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-cai-liao-gai-kuang.md
              - 日誌 / 工地人員: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-gong-di-ren-yuan.md
              - 日誌 / 機具管理: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-ji-ju-guan-li.md
              - 日誌 / 本日是否需要技術士: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-ben-ri-shi-fou-xu-yao-ji-shu-shi.md
              - 日誌 / 環安衛確認事項: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-huan-an-wei-que-ren-shi-xiang.md
              - 日誌 / 工地取樣試驗紀錄、協力廠商辦理事項、重要事項紀錄: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-gong-di-qu-yang-shi-yan-ji-lu-xie-li-chang-shang-ban-li-shi-xiang-zhong-yao-shi-xiang-ji-lu.md
              - 日誌 / 技術士簽章表: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-ji-shu-shi-qian-zhang-biao.md
              - 日誌 / 其他紀錄: pc/pc_diary/shi-gong-ri-zhi/ri-zhi-qi-ta-ji-lu.md
              - 列印日誌: pc/pc_diary/shi-gong-ri-zhi/lie-yin-ri-zhi.md
          - 日誌 / 更多紀錄事項: pc/pc_diary/ri-zhi-geng-duo-ji-lu-shi-xiang.md
          - 日誌系統設定:
              - pc/pc_diary/ri-zhi-xi-tong-she-ding/index.md
              - 基本設定: pc/pc_diary/ri-zhi-xi-tong-she-ding/ji-ben-she-ding.md
              - 預計進度設定: pc/pc_diary/ri-zhi-xi-tong-she-ding/yu-ji-jin-du-she-ding.md
              - 欄位重點提示設定: pc/pc_diary/ri-zhi-xi-tong-she-ding/lan-wei-zhong-dian-ti-shi-she-ding.md
              - 施工日誌分享: pc/pc_diary/ri-zhi-xi-tong-she-ding/shi-gong-ri-zhi-fen-xiang.md
      - 公共工程監造日報:
          - pc/supervisor-diary/index.md
          - 監造日報:
              - pc/supervisor-diary/report-detail/index.md
              - 日報 / 基本資訊: pc/supervisor-diary/report-detail/ri-bao-ji-ben-zi-xun.md
              - 日報 / 施工概況: pc/supervisor-diary/report-detail/ri-bao-shi-gong-gai-kuang.md
              - 日報 / 監督依照設計圖說施工、查核材料規格及品質、其他約定監造事項: pc/supervisor-diary/report-detail/ri-bao-jian-du-yi-zhao-she-ji-tu-shuo-shi-gong-cha-he-cai-liao-gui-ge-ji-pin-zhi-qi-ta-yue-ding-jian.md
              - 日報 / 督導工地職業安全衛生事項: pc/supervisor-diary/report-detail/ri-bao-du-dao-gong-di-zhi-ye-an-quan-wei-sheng-shi-xiang.md
              - 日報 / 其他應檢附之文件: pc/supervisor-diary/report-detail/ri-bao-qi-ta-ying-jian-fu-zhi-wen-jian.md
              - 日報 / 其他紀錄: pc/supervisor-diary/report-detail/ri-bao-qi-ta-ji-lu.md
              - 列印日報: pc/supervisor-diary/report-detail/lie-yin-ri-bao.md
              - 日報 / 其他紀錄: AMdbDE0Q14fhucG1fWgH.md
          - 日報 / 更多紀錄事項: pc/supervisor-diary/ri-bao-geng-duo-ji-lu-shi-xiang.md
          - 日報系統設定:
              - pc/supervisor-diary/system-settings/index.md
              - 監造日報分享: pc/supervisor-diary/system-settings/jian-zao-ri-bao-fen-xiang.md
              - 預計進度設定: kJKND4sGcMpmdiGDskzP.md
              - 欄位重點提示設定: d8csboPAEWporVhJfjoP.md
      - 影音日誌: 7VmzD2L7tae66VMbtO32.md
      - 檢查表: C4NGPzAxT7ZzRah4D72h.md
      - 會議紀錄: SnJxu3W1m4X4tXpuCkvh.md
      - 材料(設備)抽檢試驗:
          - pc/material_test/index.md
          - 基本設定-材料管理: FR766BRRwyUZElVauGN7.md
          - 材料檢試驗: pc/material_test/cai-liao-jian-shi-yan.md
          - 申請檢試驗: pc/material_test/shen-qing-jian-shi-yan.md
          - 檢驗結果紀錄: pc/material_test/jian-yan-jie-guo-ji-lu.md
      - 監造抽查紀錄表**: WVtOxq8dRr0GGAkf0Q4u.md
      - 缺失抽查單**: ovw8Bedrtmx22UEvHPVz.md
      - 點工管理**: RmjtdCY8iXeLCYSLKlR3.md
      - 晴雨表**: VCo3XFAtghoItFmUAprE.md
      - 進出管制**: Gn1TXv6KmNu9AoPdyeKj.md
      - 職安衛自動檢查計劃**: pnS0XDIFjntfEZVUk9bH.md
      - 設備盤點**: 6BCJLel1CDzKjI4IppCI.md
  - 人力派遣 TW:
      - tw/index.md
      - 功能概述: tw/gong-neng-gai-shu.md
      - 公司分公司基本資料: tw/compinfo.md
      - 派遣工管理: tw/resource.md
      - 客戶管理: tw/customer.md
      - 案場合約: tw/contract.md
      - 需求單與派遣: tw/requirement.md
      - 出勤表: tw/attendance.md
      - 被派遣人員APP: tw/bei-pai-qian-ren-yuan-app.md
  - 製造施工 PMC**: pmc.md
  - 現場服務 FSM**: fsm.md
  - 場域維運 O&M**: onm.md
